apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: pv-azure-file
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com 
    readOnly: false
    volumeHandle: aks-kubeflow-volume
    volumeAttributes:
      resourceGroup: intel-aks-kubeflow
      shareName: kubeflow-file-share
    nodeStageSecretRef:
      name: azure-secret
      namespace: default 
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl